// React/src/App.tsx
import React, {
  useCallback, useEffect, useMemo, useState,
} from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import FileUploader from 'devextreme-react/file-uploader';
import LoadPanel from 'devextreme-react/load-panel';
import UploadInfo from 'devextreme/file_management/upload_info';
import { UploadedEvent } from 'devextreme/ui/file_uploader';
import { AmazonGateway } from './services/amazon.gateway';
import { AmazonFileSystem } from './services/amazon.filesystem';

const endpointUrl = 'https://localhost:52366/api/AmazonS3';
const loadPanelPosition = { of: '#widget-area' };

function App(): JSX.Element {
  const [requests, setRequests] = useState<{ method: string; urlPath: string; queryString: string }[]>([]);
  const [loadPanelVisible, setLoadPanelVisible] = useState<boolean>(true);
  const [wrapperClassName, setWrapperClassName] = useState<string>('');
  const [downloadFileName, setDownloadFileName] = useState<string>('');
  const [downloadUrl, setDownloadUrl] = useState<string>('');
  const [downloadPanelVisible, setDownloadPanelVisible] = useState<boolean>(false);

  const uploadChunk = useCallback((file: File, uploadInfo: UploadInfo): Promise<any> => amazon.uploadFileChunk(file, uploadInfo, undefined), []);
  const abortUpload = useCallback((file: File, uploadInfo: UploadInfo | undefined): Promise<any> => amazon.abortFileUpload(file, uploadInfo, undefined), []);
  const onValueChanged = useCallback((): void => {
    setDownloadPanelVisible(false);
    setDownloadFileName('');
    setDownloadUrl('');
  }, []);

  const onUploaded = useCallback((e: UploadedEvent): void => {
    amazon.getPresignedDownloadUrl(e.file.name).then((url: string) => {
      setDownloadFileName(e.file.name);
      setDownloadUrl(url);
      setDownloadPanelVisible(true);
    }).catch((error: any) => {
      throw error;
    });
  }, []);

  useEffect(() => {
    fetch('https://localhost:52366/api/AmazonS3/getItems')
      .then((response) => response.json())
      .then((result) => {
        result.active = true;
        const className = result.active ? 'show-widget' : 'show-message';
        setWrapperClassName(className);
        setLoadPanelVisible(false);
      })
      .catch(() => { });
  }, []);
  const onRequestExecuted = useCallback(({ method, urlPath, queryString }: { method: string; urlPath: string; queryString: string }): void => {
    const request = { method, urlPath, queryString };
    setRequests((requests) => [request, ...requests]);
  }, []);

  const gateway = useMemo((): AmazonGateway => new AmazonGateway(endpointUrl, onRequestExecuted), []);
  const amazon = useMemo((): AmazonFileSystem => new AmazonFileSystem(gateway), []);
  return (
    <div id="wrapper" className={wrapperClassName}>
      <LoadPanel visible={loadPanelVisible} position={loadPanelPosition} />
      <div id="widget-area">
        <FileUploader id="file-uploader"
          chunkSize={5242880}
          uploadChunk={uploadChunk}
          abortUpload={abortUpload}
          onUploaded={onUploaded}
          onValueChanged={onValueChanged}
        />
        {downloadPanelVisible && (
          <div id="download-panel">
            <span>Download uploaded file:</span>
            <a href={downloadUrl} target="_blank">{downloadFileName}</a>
          </div>
        )}
        <div id="request-panel">
          {
            requests.map((r, i) => <div key={i} className="request-info">
              <div className="parameter-info">
                <div className="parameter-name">Method:</div>
                <div className="parameter-value dx-theme-accent-as-text-color">{r.method}</div>
              </div>
              <div className="parameter-info">
                <div className="parameter-name">Url path:</div>
                <div className="parameter-value dx-theme-accent-as-text-color">{r.urlPath}</div>
              </div>
              <div className="parameter-info">
                <div className="parameter-name">Query string:</div>
                <div className="parameter-value dx-theme-accent-as-text-color">{r.queryString}</div>
              </div>
              <br />
            </div>)
          }
        </div>
      </div>
      <div id="message-box">
          To run the demo locally, specify your Amazon access key, secret key,
          region and bucket name in the web.config file.
      </div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { lastValueFrom } from 'rxjs';

import UploadInfo from 'devextreme/file_management/upload_info';
import { ValueChangedEvent, UploadedEvent } from 'devextreme/ui/file_uploader';

import { AmazonGateway } from './services/amazon.gateway';
import { AmazonFileSystem } from './services/amazon.filesystem';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  requests: any[];

  wrapperClassName: string;

  loadPanelVisible: boolean;

  downloadFileName: string;

  downloadUrl: string;

  gateway: AmazonGateway;

  amazon: AmazonFileSystem;

  downloadPanelVisible: boolean;

  constructor(http: HttpClient) {
    const endpointUrl = 'https://localhost:52366/api/AmazonS3';
    this.gateway = new AmazonGateway(endpointUrl, this.onRequestExecuted.bind(this));
    this.amazon = new AmazonFileSystem(this.gateway);

    this.requests = [];
    this.wrapperClassName = '';
    this.loadPanelVisible = true;
    this.downloadFileName = '';
    this.downloadUrl = '';
    this.downloadPanelVisible = false;

    this.checkAmazonStatus(http);
    this.uploadChunk = this.uploadChunk.bind(this);
    this.abortUpload = this.abortUpload.bind(this);
    this.onUploaded = this.onUploaded.bind(this);
    this.onValueChanged = this.onValueChanged.bind(this);
  }

  async uploadChunk(file: File, uploadInfo: UploadInfo): Promise<any> {
    return this.amazon.uploadFileChunk(file, uploadInfo, undefined);
  }

  async abortUpload(file: File, uploadInfo?: UploadInfo): Promise<any> {
    return this.amazon.abortFileUpload(file, uploadInfo, undefined);
  }

  async onUploaded(e: UploadedEvent): Promise<any> {
    const url = await this.amazon.getPresignedDownloadUrl(e.file.name);
    this.downloadFileName = e.file.name;
    this.downloadUrl = url;
    this.downloadPanelVisible = true;
  }

  onValueChanged(e: ValueChangedEvent): void {
    this.downloadPanelVisible = false;
    this.downloadFileName = '';
    this.downloadUrl = '';
  }

  onRequestExecuted({ method, urlPath, queryString }: { method: string; urlPath: string; queryString: string }): void {
    const request = { method, urlPath, queryString };
    this.requests.unshift(request);
  }

  checkAmazonStatus(http: HttpClient): void {
    lastValueFrom(http.get<{ active: boolean }>('https://localhost:52366/api/AmazonS3/getItems'))
      .then((result) => {
        result.active = true;
        this.wrapperClassName = result.active ? 'show-widget' : 'show-message';
        this.loadPanelVisible = false;
      })
      .catch(() => { });
  }
}

<div id="wrapper" [class]="wrapperClassName">
  <dx-load-panel
    [position]="{ of: '#widget-area' }"
    [(visible)]="loadPanelVisible"
  >
  </dx-load-panel>
  <div id="widget-area">
    <dx-file-uploader
      id="file-uploader"
      [chunkSize]="5242880"
      [uploadChunk]="uploadChunk"
      [abortUpload]="abortUpload"
      (onUploaded)="onUploaded($event)"
      (onValueChanged)="onValueChanged($event)"
    >
    </dx-file-uploader>
    <div id="download-panel" *ngIf="downloadPanelVisible">
      <span>Download uploaded file:</span>
      <a href="{{ downloadUrl }}" target="_blank">{{ downloadFileName }}</a>
    </div>
    <div id="request-panel">
      <div class="request-info" *ngFor="let request of requests">
        <div class="parameter-info">
          <div class="parameter-name">Method:</div>
          <div class="parameter-value dx-theme-accent-as-text-color">{{
            request.method
          }}</div>
        </div>
        <div class="parameter-info">
          <div class="parameter-name">Url path:</div>
          <div class="parameter-value dx-theme-accent-as-text-color">{{
            request.urlPath
          }}</div>
        </div>
        <div class="parameter-info">
          <div class="parameter-name">Query string:</div>
          <div class="parameter-value dx-theme-accent-as-text-color">{{
            request.queryString
          }}</div>
        </div>
        <br />
      </div>
    </div>
  </div>
  <div id="message-box">
    To run the demo locally, specify your Amazon access key, secret key region
    and blob names in the web.config file.
  </div>
</div>
